package br.com.xiquimvargas.seller

import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import org.json.*

class MainActivity:Activity(){
 private var token="";private lateinit var box:LinearLayout;private var clients=JSONArray();private var products=JSONArray();private var selectedClient=""
 private fun tv(t:String,size:Float=16f)=TextView(this).apply{ text=t;textSize=size;setTextColor(Color.WHITE);setPadding(8,8,8,8) }
 override fun onCreate(b:Bundle?){super.onCreate(b);login()}
 private fun login(){box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,50,24,24);setBackgroundColor(Color.rgb(7,12,24))};box.addView(tv("Xiquim Vargas\nVendedor Externo",26f));val e=EditText(this);e.hint="Email";box.addView(e);val p=EditText(this);p.hint="Senha";box.addView(p);val b=Button(this);b.text="Entrar";box.addView(b);b.setOnClickListener{Thread{try{val r=Api.request("/api/auth/login","POST",body="{\"email\":\"${e.text}\",\"password\":\"${p.text}\"}");token=JSONObject(r).getString("token");runOnUiThread{home()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()};setContentView(box)}
 private fun home(){box.removeAllViews();box.addView(tv("Minha carteira",24f));Thread{try{clients=JSONObject(Api.request("/api/clients",token=token)).getJSONArray("items");products=JSONObject(Api.request("/api/products",token=token)).getJSONArray("items");runOnUiThread{renderHome()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()}
 private fun renderHome(){val s=Spinner(this);val names=ArrayList<String>();for(i in 0 until clients.length())names.add(clients.getJSONObject(i).optString("razao_social"));s.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names);box.addView(s);val order=Button(this);order.text="Novo pedido";box.addView(order);order.setOnClickListener{if(clients.length()>0){selectedClient=clients.getJSONObject(s.selectedItemPosition).getString("id");newOrder()}};val refresh=Button(this);refresh.text="Atualizar carteira";box.addView(refresh);refresh.setOnClickListener{home()};val out=Button(this);out.text="Sair";box.addView(out);out.setOnClickListener{token="";login()}}
 private fun newOrder(){box.removeAllViews();box.addView(tv("Novo pedido",24f));val quantities=IntArray(products.length());for(i in 0 until products.length()){val p=products.getJSONObject(i);val row=LinearLayout(this);row.orientation=LinearLayout.HORIZONTAL;val label=tv("${p.optString("nome")}  R$ ${"%.2f".format(p.optDouble("preco_base"))}  estoque ${p.optInt("quantidade_disponivel")}");row.addView(label,LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));val q=EditText(this);q.inputType=2;q.hint="0";row.addView(q,LinearLayout.LayoutParams(90,LinearLayout.LayoutParams.WRAP_CONTENT));q.tag=i;row.tag=q;box.addView(row)};val send=Button(this);send.text="Emitir pedido";box.addView(send);send.setOnClickListener{val items=JSONArray();for(i in 0 until box.childCount){val v=box.getChildAt(i);if(v.tag is EditText){val q=(v.tag as EditText).text.toString().toIntOrNull()?:0;if(q>0){val p=products.getJSONObject((v.tag as EditText).tag as Int);items.put(JSONObject().put("produto_id",p.getString("id")).put("quantidade",q))}}};if(items.length()==0)return@setOnClickListener;Thread{try{val r=Api.request("/api/orders","POST",token,"{\"cliente_id\":\"$selectedClient\",\"itens\":$items,\"origem\":\"VENDEDOR\"}");runOnUiThread{Toast.makeText(this,"Pedido ${JSONObject(r).getJSONObject("item").getString("numero")} criado",Toast.LENGTH_LONG).show();home()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()};val back=Button(this);back.text="Voltar";box.addView(back);back.setOnClickListener{home()}}
}
