package br.com.xiquimvargas.driver

import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.net.Uri;import android.util.Base64;import android.view.*;import android.widget.*;import org.json.*

class MainActivity:Activity(){
 private var token="";private lateinit var box:LinearLayout;private var proofOrder="";private val PICK=77
 private fun tv(t:String,size:Float=16f)=TextView(this).apply{text=t;textSize=size;setTextColor(Color.WHITE);setPadding(8,8,8,8)}
 override fun onCreate(b:Bundle?){super.onCreate(b);login()}
 private fun login(){box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,50,24,24);setBackgroundColor(Color.rgb(7,12,24))};box.addView(tv("Xiquim Vargas\nMotorista",26f));val e=EditText(this);e.hint="Email";box.addView(e);val p=EditText(this);p.hint="Senha";box.addView(p);val b=Button(this);b.text="Entrar";box.addView(b);b.setOnClickListener{Thread{try{val r=Api.request("/api/auth/login","POST",body="{\"email\":\"${e.text}\",\"password\":\"${p.text}\"}");token=JSONObject(r).getString("token");runOnUiThread{home()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()};setContentView(box)}
 private fun home(){Thread{try{val routes=JSONObject(Api.request("/api/logistics/routes",token=token)).getJSONArray("items");val orders=JSONObject(Api.request("/api/orders",token=token)).getJSONArray("items");val map=HashMap<String,JSONObject>();for(i in 0 until orders.length()){val o=orders.getJSONObject(i);map[o.getString("id")]=o};runOnUiThread{render(routes,map)}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()}
 private fun render(routes:JSONArray,map:HashMap<String,JSONObject>){box.removeAllViews();box.addView(tv("Fila do dia",24f));for(r in 0 until routes.length()){val ids=JSONArray(routes.getJSONObject(r).optString("sequencia_json","[]"));for(i in 0 until ids.length()){val o=map[ids.getString(i)]?:continue;val card=LinearLayout(this);card.orientation=LinearLayout.VERTICAL;card.setPadding(12,12,12,12);card.addView(tv("Parada ${i+1} — ${o.optString("numero")}"));card.addView(tv(o.optString("cliente_nome")));card.addView(tv(o.optString("cliente_endereco","Endereço não informado")));val maps=Button(this);maps.text="Abrir no Maps";card.addView(maps);maps.setOnClickListener{val q=Uri.encode(o.optString("cliente_endereco"));startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/search/?api=1&query=$q")))};val proof=Button(this);proof.text="Anexar canhoto";card.addView(proof);proof.setOnClickListener{proofOrder=o.getString("id");startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE)},PICK)};val done=Button(this);done.text="Concluído";card.addView(done);done.setOnClickListener{complete(o.getString("id"))};box.addView(card)}};val out=Button(this);out.text="Sair";box.addView(out);out.setOnClickListener{token="";login()}}
 private fun complete(id:String){Thread{try{Api.request("/api/logistics/orders/$id/complete","POST",token,"{}");runOnUiThread{Toast.makeText(this,"Entrega concluída",Toast.LENGTH_SHORT).show();home()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=PICK||resultCode!=RESULT_OK||data?.data==null)return;Thread{try{val bytes=contentResolver.openInputStream(data.data!!)?.use{it.readBytes()}?:throw Exception("Arquivo vazio");val b64=Base64.encodeToString(bytes,Base64.NO_WRAP);Api.request("/api/logistics/orders/$proofOrder/proof","POST",token,"{\"data_url\":\"data:image/jpeg;base64,$b64\"}");runOnUiThread{Toast.makeText(this,"Canhoto anexado",Toast.LENGTH_SHORT).show()}}catch(x:Exception){runOnUiThread{Toast.makeText(this,x.message,Toast.LENGTH_LONG).show()}}}.start()}
}
