import { DatabaseSync } from 'node:sqlite';
const BASE='http://127.0.0.1:3200';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const req=async(p,o={})=>{const r=await fetch(BASE+p,o);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}return{s:r.status,d}};
const auth=(t,p,o={})=>req(p,{...o,headers:{'content-type':'application/json',...(t?{authorization:`Bearer ${t}`}:{})}});
const login=async(e,p)=>{const r=await req('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:e,password:p})});if(r.s!==200)throw Error(`login ${e}`);return r.d.token};
const A=(v,m)=>{if(!v)throw Error(m)};
const db=()=>new DatabaseSync('storage/xiquim-vargas.db');
const admin=await login('admin@xiquimvargas.local','Admin@123');
const seller=await login('vendedor@xiquimvargas.local','Vendedor@123');
const cash=await login('caixa@xiquimvargas.local','Caixa@123');
const driver=await login('motorista@xiquimvargas.local','Motorista@123');
const web=await login('cliente@xiquimvargas.local','Cliente@123');
const clients=(await auth(seller,'/api/clients')).d.items;A(clients.length>=1,'seller carteira seed');
const client=clients[0];
const products=(await auth(seller,'/api/products?limit=100')).d.items;const product=products.find(x=>x.quantidade_disponivel>=60);A(product,'produto com estoque');
const did=(await auth(admin,'/api/users')).d.items.find(x=>x.role==='driver').id;
for(let i=1;i<=50;i++){
  A((await req('/health')).s===200,'health');
  for(const [name,t] of [['seller',seller],['cash',cash],['driver',driver],['web',web]]) A((await auth(t,'/api/dashboard')).s===403,`RBAC ${name}`);
  const page=(await auth(seller,'/api/products?page=1&limit=2')).d;A(page.items.length<=2&&page.total>=4,'pagination');
  A((await auth(seller,`/api/stock/${product.id}/movements`)).s===200,'stock movements');
  const before=Number((await auth(admin,'/api/stock')).d.items.find(x=>x.id===product.id).quantidade_disponivel);
  const o=(await auth(seller,'/api/orders',{method:'POST',body:JSON.stringify({cliente_id:client.id,itens:[{produto_id:product.id,quantidade:1}],origem:'BALCAO',preco:0,observacoes:`loop-${i}`})}));
  A(o.s===201,`create order ${i}`);const oid=o.d.item.id;A(o.d.item.origem==='VENDEDOR','seller origin enforcement');A(Math.abs(Number(o.d.item.total)-Number(product.preco_base))<0.001,'server price authority');A(o.d.item.pdf_path,'pdf generated');
  A((await auth(seller,`/api/orders/${oid}/status`,{method:'POST',body:JSON.stringify({status:'ROTA'})})).s===403,'seller cannot transition');
  A((await auth(admin,`/api/orders/${oid}/status`,{method:'POST',body:JSON.stringify({status:'ROTA'})})).s===409,'status bypass blocked');
  A((await auth(admin,`/api/logistics/orders/${oid}/proof`,{method:'POST',body:JSON.stringify({data_url:'data:image/jpeg;base64,/9j/4AAQ'})})).s===409,'proof before route blocked');
  A((await auth(admin,`/api/orders/${oid}/status`,{method:'POST',body:JSON.stringify({status:'SEPARACAO'})})).s===200,'separation');
  const route=(await auth(admin,'/api/logistics/routes',{method:'POST',body:JSON.stringify({pedido_ids:[oid],motorista_id:did})}));A(route.s===201,`route ${i}`);
  A((await auth(admin,'/api/logistics/routes',{method:'POST',body:JSON.stringify({pedido_ids:[oid],motorista_id:did})})).s===409,'duplicate route');
  A((await auth(driver,`/api/logistics/orders/${oid}/proof`,{method:'POST',body:JSON.stringify({data_url:'data:image/jpeg;base64,/9j/4AAQ'})})).s===201,'proof');
  A((await auth(driver,`/api/logistics/orders/${oid}/complete`,{method:'POST',body:'{}'})).s===200,'complete');
  A((await auth(driver,`/api/logistics/orders/${oid}/complete`,{method:'POST',body:'{}'})).s===409,'double complete');
  A((await auth(seller,`/api/orders/${oid}/pdf`)).s===200,'pdf access');
  A((await req('/storage/../src/db.js')).s!==200,'path traversal');
  const afterStock=Number((await auth(admin,'/api/stock')).d.items.find(x=>x.id===product.id).quantidade_disponivel);A(afterStock===before-1,`stock decrement ${i}`);
  const auditRows=(await auth(admin,'/api/audit')).d.items;A(auditRows.some(a=>a.entity_id===oid),'audit');
  console.log(`HARDENING LOOP ${i}/50 PASS`);
  await sleep(12000);
}
const d=db();const finalStock=d.prepare('SELECT quantidade_disponivel,quantidade_reservada FROM estoque WHERE produto_id=?').get(product.id);A(finalStock.quantidade_disponivel>=0&&finalStock.quantidade_reservada===0,'final stock');d.close();
console.log('HARDENING 50/50 COMPLETE');
