import {spawn} from 'node:child_process';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
const BASE='http://127.0.0.1:3200';const sleep=ms=>new Promise(r=>setTimeout(r,ms));const req=async(p,o={})=>{const r=await fetch(BASE+p,o);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}return {s:r.status,d}};const auth=(t,p,o={})=>req(p,{...o,headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})}});const login=async(e,p)=>{const r=await req('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:e,password:p})});if(r.s!==200)throw Error('login');return r.d.token};const A=(c,m)=>{if(!c)throw Error(m)};
fs.rmSync('storage/xiquim-vargas.db',{force:true});await new Promise((res,rej)=>{const p=spawn('npm',['run','seed'],{stdio:'ignore'});p.on('exit',c=>c?rej(Error('seed')):res())});const server=spawn('node',['server.js'],{env:{...process.env,PORT:'3200'},stdio:'ignore'});for(let i=0;i<30;i++){try{if((await req('/health')).s===200)break}catch{}await sleep(50)}
const admin=await login('admin@xiquimvargas.local','Admin@123'),seller=await login('vendedor@xiquimvargas.local','Vendedor@123'),cash=await login('caixa@xiquimvargas.local','Caixa@123'),driver=await login('motorista@xiquimvargas.local','Motorista@123'),web=await login('cliente@xiquimvargas.local','Cliente@123');const c=(await auth(seller,'/api/clients')).d.items[0];const prod=(await auth(seller,'/api/products')).d.items.find(x=>x.quantidade_disponivel>60);const did=(await auth(admin,'/api/users')).d.items.find(x=>x.role==='driver').id;
for(let i=1;i<=50;i++){
 A((await req('/storage/pdfs/nope.pdf')).s===401,'storage');
 for(const t of [seller,cash,driver,web])A((await auth(t,'/api/dashboard')).s===403,'rbac');
 const o=(await auth(seller,'/api/orders',{method:'POST',body:JSON.stringify({cliente_id:c.id,itens:[{produto_id:prod.id,quantidade:1}],origem:'BALCAO',preco:0})}));A(o.s===201,'order');const id=o.d.item.id;
 A((await auth(admin,`/api/orders/${id}/status`,{method:'POST',body:JSON.stringify({status:'ROTA'})})).s===409,'bypass');A((await auth(admin,`/api/orders/${id}/status`,{method:'POST',body:JSON.stringify({status:'SEPARACAO'})})).s===200,'separation');A((await auth(admin,'/api/logistics/routes',{method:'POST',body:JSON.stringify({pedido_ids:[id],motorista_id:did})})).s===201,'route');A((await auth(admin,'/api/logistics/routes',{method:'POST',body:JSON.stringify({pedido_ids:[id],motorista_id:did})})).s===409,'dup route');A((await auth(driver,`/api/logistics/orders/${id}/complete`,{method:'POST',body:'{}'})).s===200,'complete');A((await auth(driver,`/api/logistics/orders/${id}/complete`,{method:'POST',body:'{}'})).s===409,'idempotence');A((await auth(seller,`/api/orders/${id}/pdf`)).s===200,'pdf');
 const db=new DatabaseSync('storage/xiquim-vargas.db');A(db.prepare('PRAGMA integrity_check').get().integrity_check==='ok','integrity');A(!db.prepare('PRAGMA foreign_key_check').all().length,'fk');const st=db.prepare('SELECT quantidade_disponivel,quantidade_reservada FROM estoque WHERE produto_id=?').get(prod.id);A(st.quantidade_disponivel>=0&&st.quantidade_reservada>=0,'stock');db.close();
 console.log(`FINAL LOOP ${i}/50 PASS`)
}
server.kill();
