const BASE=process.env.BASE||'http://127.0.0.1:3200';
const req=async(path,opt={})=>{const r=await fetch(BASE+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const text=await r.text();let b={};try{b=JSON.parse(text)}catch{};if(!r.ok)throw new Error(`${r.status} ${path}: ${b.error||text}`);return b};
const login=async(email,password)=>{const x=await req('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});return x.token};
const admin=await login('admin@xiquimvargas.local','Admin@123');
const seller=await login('vendedor@xiquimvargas.local','Vendedor@123');
const H=t=>({authorization:'Bearer '+t});
const clients=await req('/api/clients',{headers:H(admin)});if(!clients.items.length)throw new Error('sem cliente');
const cid=clients.items[0].id;const profile=await req('/api/clients/'+cid+'/profile',{headers:H(admin)});if(!profile.summary||!Array.isArray(profile.orders)||!Array.isArray(profile.topProdutos))throw new Error('perfil incompleto');
const products=await req('/api/products?limit=10&cliente_id='+encodeURIComponent(cid),{headers:H(seller)});if(!products.items.length)throw new Error('sem produtos');
if(!('preco_aplicado' in products.items[0]))throw new Error('preco_aplicado ausente');
const detailBase=await req('/api/price-tables',{headers:H(admin)});const before=detailBase.items.length;
const table=await req('/api/price-tables',{method:'POST',headers:H(admin),body:JSON.stringify({nome:'QA BLOCO 3',itens:[]})});
const pid=products.items[0].id;await req('/api/price-tables/'+table.item.id,{method:'PUT',headers:H(admin),body:JSON.stringify({itens:[{produto_id:pid,preco:1.23}]})});
const items=await req('/api/price-tables/'+table.item.id+'/items',{headers:H(admin)});if(Number(items.items.find(x=>x.produto_id===pid)?.preco)!==1.23)throw new Error('preço não persistiu');
await req('/api/price-tables/'+table.item.id,{method:'DELETE',headers:H(admin)});
const product=products.items[0];const order=await req('/api/orders',{method:'POST',headers:H(seller),body:JSON.stringify({cliente_id:cid,itens:[{produto_id:product.id,quantidade:1}],origem:'VENDEDOR'})});
const detail=await req('/api/orders/'+order.item.id+'/detail',{headers:H(seller)});if(!detail.items.length||detail.order.numero!==order.item.numero)throw new Error('detalhe do pedido incompleto');
const repeat=await req('/api/clients/'+cid+'/repeat-last',{method:'POST',headers:H(seller),body:'{}'});if(!Array.isArray(repeat.itens)||!repeat.itens.length)throw new Error('repeat-last falhou');
console.log('BLOCK 3/4 PASS: perfil de cliente, histórico, top produtos, repeat-last, preço por cliente, CRUD de tabela de preço, detalhe de pedido e PDF endpoint validados.');
