import {DatabaseSync} from 'node:sqlite';
const BASE=process.env.BASE||'http://127.0.0.1:3000';
const req=async(p,o={})=>{const r=await fetch(BASE+p,o);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}return{s:r.status,d}};
const login=async(e,p)=>{const r=await req('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:e,password:p})});if(r.s!==200)throw Error('login '+r.s);return r.d.token};
const auth=(t,p,o={})=>req(p,{...o,headers:{'content-type':'application/json',authorization:`Bearer ${t}`}});
const A=(x,m)=>{if(!x)throw Error(m)};
const admin=await login('admin@xiquimvargas.local','Admin@123');
const seller=await login('vendedor@xiquimvargas.local','Vendedor@123');
A((await auth(seller,'/api/products',{method:'POST',body:JSON.stringify({nome:'blocked',sku:'BLOCK-'+Date.now(),preco_base:1})})).s===403,'seller product write must be denied');
const stamp=Date.now();
const cat=(await auth(admin,'/api/categories',{method:'POST',body:JSON.stringify({nome:'QA Categoria '+stamp,descricao:'bloco12'})}));A(cat.s===201,'category create');
const cid=cat.d.item.id;
const sub=(await auth(admin,'/api/subcategories',{method:'POST',body:JSON.stringify({categoria_id:cid,nome:'QA Sub '+stamp})}));A(sub.s===201,'subcategory create');
const sid=sub.d.item.id;
const product=(await auth(admin,'/api/products',{method:'POST',body:JSON.stringify({nome:'QA Produto '+stamp,sku:'QA-'+stamp,codigo_barras:'QA-BAR-'+stamp,categoria_id:cid,subcategoria_id:sid,preco_base:12.34,quantidade:10,estoque_minimo:3})}));A(product.s===201,'product create');
const pid=product.d.item.id;A(product.d.item.nome.includes('QA Produto'),'product persisted');
const hist=(await auth(admin,`/api/stock/${pid}/movements`));A(hist.s===200&&hist.d.items.some(x=>x.tipo==='ENTRADA_INICIAL'&&x.quantidade===10),'initial stock movement');
const incompatible=(await auth(admin,`/api/products/${pid}`,{method:'PUT',body:JSON.stringify({categoria_id:'does-not-exist',subcategoria_id:sid})}));A(incompatible.s===400,'invalid category rejected');
const adjusted=(await auth(admin,`/api/stock/${pid}`,{method:'POST',body:JSON.stringify({delta:5,tipo:'ENTRADA',observacao:'qa'})}));A(adjusted.s===200&&adjusted.d.item.quantidade_disponivel===15,'stock adjustment');
const finalHist=(await auth(admin,`/api/stock/${pid}/movements`));A(finalHist.d.items.length>=2,'stock history retained');
const db=new DatabaseSync('storage/xiquim-vargas.db');db.exec('PRAGMA foreign_keys=ON');db.prepare('DELETE FROM movimentacoes_estoque WHERE produto_id=?').run(pid);db.prepare('DELETE FROM estoque WHERE produto_id=?').run(pid);db.prepare('DELETE FROM produtos WHERE id=?').run(pid);db.prepare('DELETE FROM subcategorias WHERE id=?').run(sid);db.prepare('DELETE FROM categorias WHERE id=?').run(cid);db.close();
console.log('BLOCK 1/2 PASS: auth hardening, catalog governance, initial stock ledger, history, validation and RBAC.');
