import {db,id,run,one} from '../src/db.js';import {hashPassword} from '../src/auth.js';
const users=[['Administrador','admin@xiquimvargas.local','admin','Admin@123'],['Vendedor Externo','vendedor@xiquimvargas.local','seller','Vendedor@123'],['Caixa','caixa@xiquimvargas.local','cashier','Caixa@123'],['Motorista','motorista@xiquimvargas.local','driver','Motorista@123'],['Cliente Web','cliente@xiquimvargas.local','web_client','Cliente@123']];
for(const [nome,email,role,p] of users)if(!one('SELECT id FROM usuarios WHERE email=?',[email]))run('INSERT INTO usuarios(id,nome,email,senha_hash,role) VALUES(?,?,?,?,?)',[id(),nome,email,hashPassword(p),role]);
const admin=one('SELECT id FROM usuarios WHERE email=?',['admin@xiquimvargas.local']);const seller=one('SELECT id FROM usuarios WHERE email=?',['vendedor@xiquimvargas.local']);
const cat=one('SELECT id FROM categorias WHERE slug=?',['bebidas-nao-alcoolicas'])||(()=>{const x=id();run('INSERT INTO categorias(id,nome,slug,descricao,ordem) VALUES(?,?,?,?,?)',[x,'Bebidas não alcoólicas','bebidas-nao-alcoolicas','Bebidas para varejo e atacado',1]);return {id:x}})();
const subs=[['refrigerantes','Refrigerantes'],['sucos','Sucos'],['energeticos','Energéticos'],['agua-mineral','Água mineral']];for(const [slug,nome] of subs)if(!one('SELECT id FROM subcategorias WHERE categoria_id=? AND slug=?',[cat.id,slug]))run('INSERT INTO subcategorias(id,categoria_id,nome,slug,ordem) VALUES(?,?,?,?,?)',[id(),cat.id,nome,slug,1]);
const table=one('SELECT id FROM tabelas_preco WHERE nome=?',['Varejo'])||(()=>{const x=id();run('INSERT INTO tabelas_preco(id,nome) VALUES(?,?)',[x,'Varejo']);return {id:x}})();
const sub=one('SELECT id FROM subcategorias WHERE categoria_id=? ORDER BY ordem LIMIT 1',[cat.id]);
const products=[['Refrigerante Cola 2L','REF-COLA-2L','789000000001','Xiquim','Cola','2L','UN',8.9,120,10],['Água Mineral 500ml','AGUA-500','789000000002','Fonte X','Natural','500ml','UN',2.5,300,30],['Suco Uva 1L','SUCO-UVA-1L','789000000003','Sabor Bom','Uva','1L','UN',7.5,80,10],['Energético 473ml','ENER-473','789000000004','Power','Tradicional','473ml','UN',9.9,60,8]];
for(const x of products){let p=one('SELECT id FROM produtos WHERE sku=?',[x[1]]);if(!p){const pid=id();run('INSERT INTO produtos(id,nome,sku,codigo_barras,marca,sabor,tamanho,unidade,preco_base,categoria_id,subcategoria_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[pid,x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],cat.id,sub.id]);run('INSERT INTO estoque(produto_id,quantidade_disponivel,estoque_minimo) VALUES(?,?,?)',[pid,x[8],x[9]]);run('INSERT INTO tabela_preco_itens(id,tabela_id,produto_id,preco) VALUES(?,?,?,?)',[id(),table.id,pid,x[7]])}}
const clientUser=one('SELECT id FROM usuarios WHERE email=?',['cliente@xiquimvargas.local']);if(!one('SELECT id FROM clientes WHERE cnpj_cpf=?',['00.000.000/0001-00'])){const cid=id();run('INSERT INTO clientes(id,razao_social,nome_fantasia,cnpj_cpf,email,telefone,endereco,cidade,estado,cep,latitude,longitude,limite_credito,tabela_preco_id,vendedor_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[cid,'Cliente Demonstração','Mercado Demonstração','00.000.000/0001-00','cliente@xiquimvargas.local','(33) 99999-0000','Rua Principal, 100','Governador Valadares','MG','35000-000',-18.8515,-41.9498,5000,table.id,seller.id])}
run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['company.name','Xiquim Vargas']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['store.title','Catálogo Xiquim Vargas']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['store.subtitle','Distribuição, reposição e condições comerciais em um só lugar.']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['store.hero','Encontre produtos, condições e reposição para o seu negócio.']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['store.footer','Pedido, catálogo e operação integrados.']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['logistics.cutoff','17:00']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['depot.latitude','-18.8515']);run('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO UPDATE SET valor=excluded.valor',['depot.longitude','-41.9498']);
console.log('Seed concluído. Admin:',admin.id,'Cliente:',clientUser.id);

const wc=one('SELECT id FROM usuarios WHERE email=?',['cliente@xiquimvargas.local']);const cc=one('SELECT id FROM clientes WHERE email=?',['cliente@xiquimvargas.local']);if(wc&&cc)run('INSERT INTO usuario_clientes(usuario_id,cliente_id) VALUES(?,?) ON CONFLICT(usuario_id) DO UPDATE SET cliente_id=excluded.cliente_id',[wc.id,cc.id]);
