import fs from 'node:fs';
const CP1252={'€':'\x80','‚':'\x82','ƒ':'\x83','„':'\x84','…':'\x85','†':'\x86','‡':'\x87','ˆ':'\x88','‰':'\x89','Š':'\x8A','‹':'\x8B','Œ':'\x8C','Ž':'\x8E','‘':'\x91','’':'\x92','“':'\x93','”':'\x94','•':'\x95','–':'\x96','—':'\x97','˜':'\x98','™':'\x99','š':'\x9A','›':'\x9B','œ':'\x9C','ž':'\x9E','Ÿ':'\x9F'};
function win1252(s){return String(s??'').normalize('NFC').replace(/[€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ]/g,c=>CP1252[c]).replace(/[\u0100-\uFFFF]/g,'?')}
function esc(s){return win1252(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function wrap(s,n=94){const words=String(s??'').split(/\s+/);const out=[];let line='';for(const w of words){if((line+' '+w).trim().length>n){if(line)out.push(line);line=w}else line=(line+' '+w).trim()}if(line)out.push(line);return out.length?out:['']}
function buildPdf(pages,file){const objs=[];const add=x=>{objs.push(x);return objs.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');const pageRefs=[],contentRefs=[];for(const pg of pages){const content=['BT','/F1 10 Tf','50 800 Td'];pg.forEach((l,i)=>{if(i)content.push('0 -18 Td');content.push(`(${esc(l)}) Tj`)});content.push('ET');const stream=content.join('\n');contentRefs.push(add(`<< /Length ${Buffer.byteLength(stream,'latin1')} >>\nstream\n${stream}\nendstream`));pageRefs.push(add('PLACEHOLDER'))}const pagesObj=objs.length+1,catalogObj=pagesObj+1;for(let i=0;i<pageRefs.length;i++)objs[pageRefs[i]-1]=`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentRefs[i]} 0 R >>`;objs.push(`<< /Type /Pages /Kids [${pageRefs.map(x=>x+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`);objs.push(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);let out='%PDF-1.4\n',offs=[0];for(let i=0;i<objs.length;i++){offs.push(Buffer.byteLength(out,'latin1'));out+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const xref=Buffer.byteLength(out,'latin1');out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objs.length+1} /Root ${catalogObj} 0 R >>\nstartxref\n${xref}\n%%EOF`;fs.writeFileSync(file,Buffer.from(out,'latin1'))}
function paginate(lines){const pages=[];let page=[];for(const l of lines.flatMap(x=>wrap(x))){if(page.length>=39){pages.push(page);page=[]}page.push(l)}if(page.length)pages.push(page);return pages}
export function makeOrderPdf(order,items,file){const origin={WEB:'Loja Online',VENDEDOR:'Vendedor Externo',BALCAO:'Frente de Loja'}[order.origem]||order.origem;const lines=['XIQUIM VARGAS','DISTRIBUIÇÃO DE BEBIDAS','',`PEDIDO ${order.numero}`,`Emissão: ${new Date(order.created_at).toLocaleString('pt-BR')}`,`Modalidade: ${origin}`,`Cliente: ${order.cliente_nome}`,`Documento: ${order.cnpj_cpf||'-'}`,'','ITENS','QTD  DESCRIÇÃO                         UNITÁRIO        SUBTOTAL','--------------------------------------------------------------------------------'];for(const x of items){const desc=String(x.produto_nome||'').slice(0,32).padEnd(32,' ');lines.push(`${String(x.quantidade).padStart(3)}  ${desc}${`R$ ${Number(x.preco_unitario_aplicado).toFixed(2)}`.padStart(13)}${`R$ ${Number(x.subtotal).toFixed(2)}`.padStart(14)}`)}lines.push('','--------------------------------------------------------------------------------',`TOTAL DO PEDIDO: R$ ${Number(order.total).toFixed(2)}`,'',`Status: ${order.status}`,'Documento operacional do Xiquim Vargas ERP.');buildPdf(paginate(lines),file)}
export function makeCatalogPdf(items,file){const lines=['XIQUIM VARGAS','CATÁLOGO DE PRODUTOS',`Gerado em: ${new Date().toLocaleString('pt-BR')}`,`Total de produtos: ${items.length}`,'','PRODUTO | SKU | CATEGORIA | SUBCATEGORIA | PREÇO | PROMOÇÃO','--------------------------------------------------------------------------------'];for(const x of items)lines.push(`${String(x.nome||'').slice(0,26)} | ${String(x.sku||'').slice(0,16)} | ${String(x.categoria_nome||'-').slice(0,18)} | ${String(x.subcategoria_nome||'-').slice(0,18)} | R$ ${Number(x.preco_base||0).toFixed(2)} | ${x.promocao_preco==null?'-':'R$ '+Number(x.promocao_preco).toFixed(2)}`);buildPdf(paginate(lines),file)}
export function makeStockPdf(items,file){const lines=['XIQUIM VARGAS','RELATÓRIO DE ESTOQUE INTELIGENTE',`Gerado em: ${new Date().toLocaleString('pt-BR')}`,`Total de produtos: ${items.length}`,'','PRODUTO | SKU | DISPONÍVEL | RESERVADO | MÍNIMO | STATUS','--------------------------------------------------------------------------------'];for(const x of items)lines.push(`${String(x.nome||'').slice(0,28)} | ${String(x.sku||'').slice(0,15)} | ${x.quantidade_disponivel} | ${x.quantidade_reservada} | ${x.estoque_minimo} | ${x.status||'-'}`);buildPdf(paginate(lines),file)}
